pipeline {
    agent none
      stages{
        stage('build and test project') {
          agent {
            docker {
//            image 'sioj/maven-docker'
            image 'maven:3-alpine'
//             args '-v /root/.m2:/root/.m2'
            args '-v /tmp:/tmp  -v /root/.m2:/root/.m2'
            reuseNode true
        }
    }
        steps {
                sh "mvn clean package"
                sh "pwd"
                sh "ls -al"
                sh "cp target/spring-*.jar ./"
            }
                                       }
   stage('Docker') {
       agent any
       steps {
                    script {
                  def app_image = docker.build("sioj/jenkins-pet-helloworld:latest")
                  withCredentials([string(credentialsId: 'Dockerhub_token', variable: 'TOKEN')]) {
                  sh "docker login -u sioj -p ${TOKEN} "
                  sh "docker push sioj/jenkins-pet-helloworld"
                  sh "docker logout"
                          }
                                                                                                 }
                  }
             }


        }
 }
